name: Build and push Docker image
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
    
  
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Taking files 
        uses: actions/checkout@v3
      - name: Taking files 
        run: echo "$version" 
      - name: Login Docker account 
        uses: docker/login-action@v2 
        with:
          username: "${{ secrets.DOCKER_NAME }}" 
          password: "${{ secrets.DOCKER_PASSWORD }}" 
      - name: Build and push 
        run: | 
          docker image build -t sayam2001/assignment1 .
          docker tag sayam2001/assignment1:latest sayam2001/assignment1:$(git rev-parse --short=7 HEAD)
          docker push sayam2001/assignment1:$(git rev-parse --short=7 HEAD)
          docker pull sayam2001/assignment1:$(git rev-parse --short=7 HEAD)

  installation:
      needs: build
      runs-on: ubuntu-latest
      container:
         image: sayam2001/assignment1:$(git rev-parse --short=7 HEAD)
      steps:
            - name: updating packages
              run: apt-get update -y

              

