name: Build and push Docker image
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
    
  
jobs:
  build: 
    runs-on: ubuntu-latest
    outputs:
      sha7: ${{ steps.mysha.outputs.sha7 }}
    steps: 
      - name: Taking files 
        uses: actions/checkout@v3
      - name: getshort
        id: mysha
        run: echo "sha7=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Login Docker account 
        uses: docker/login-action@v2 
        with:
          username: "${{ secrets.DOCKER_NAME }}" 
          password: "${{ secrets.DOCKER_PASSWORD }}" 
      - name: Build and push 
        run: | 
          docker image build -t sayam2001/assignment1 .
          docker tag sayam2001/assignment1:latest sayam2001/assignment1:${{ steps.mysha.outputs.sha7 }}
          docker push sayam2001/assignment1:${{ steps.mysha.outputs.sha7 }}
          docker pull sayam2001/assignment1:${{ steps.mysha.outputs.sha7 }}

 
  installing_git:
      needs: build
      runs-on: ubuntu-latest
      container:
         image: sayam2001/assignment1:${{ needs.build.outputs.sha7 }}
      steps:
            - name: updating packages
              run: apt-get update -y
            - name: installing git
              run: apt-get install git -y
            - name: git version
              run: git --version
              
  

              

