name: Build and push Docker image
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Taking files 
        uses: actions/checkout@v3 
      - name: Login Docker account 
        uses: docker/login-action@v2 
        with:
          username: "${{ secrets.DOCKER_NAME }}" 
          password: "${{ secrets.DOCKER_PASSWORD }}" 
      - name: Build and push 
        run: | 
          docker image build -t sayam2001/assignment1:latest .
          docker tag sayam2001/assignment1:latest sayam2001/assignment1:$(git log -1 --pretty=%h)
          docker push sayam2001/assignment1:$(git log -1 --pretty=%h)
          docker pull sayam2001/assignment1:$(git log -1 --pretty=%h)
          
  
  installation:
      needs: build
      runs-on: ubuntu-latest
      container:
         image: sayam2001/assignment1:$(git log -1 --pretty=%h)
      steps:
            - name: updating packages
              run: apt-get update -y
            - name: installing git
              run: apt-get install git -y
            - name: git version
              run: git --version
              

