name: Build and push Docker image
on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Taking files 
        uses: actions/checkout@v3 
      - name: Login Docker account 
        uses: docker/login-action@v2 
        with:
          username: "${{ secrets.DOCKER_NAME }}" 
          password: "${{ secrets.DOCKER_PASSWORD }}" 
      - name: Build and push 
        run: | 
          docker image build -t sayam2001/assignment1:latest . 
          docker push sayam2001/assignment1:latest
          docker pull sayam2001/assignment1:latest
          
          runs-on: sayam2001/assignment1:latest
          steps: 
          - name: install git
            run : |
            apt-get install git -y
            git --version
